apiVersion: apps/v1
kind: Deployment
metadata:
  name: newstock-stock-auth
  labels:
    app: newstock-stock-auth
spec:
  replicas: 1  # 원하는 레플리카 수 설정
  selector:
    matchLabels:
      app: newstock-stock-auth
  template:
    metadata:
      labels:
        app: newstock-stock-auth
    spec:
      containers:
      - name: newstock-stock-auth-container
        image: ocir.ap-singapore-2.oci.oraclecloud.com/axzbwuphhddr/newstockauth:TAG_PLACEHOLDER
        ports:
        - containerPort: 8000  # 스프링 부트 애플리케이션의 기본 포트
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"



        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m"  # 메모리 설정 등 스프링 부트 설정
        - name: KIS_TOKEN_URL
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: KIS_TOKEN_URL
        - name: KIS_WEBSOCKET_TOKEN_URL
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: KIS_WEBSOCKET_TOKEN_URL
        - name: KIS_STOCK_PRICE_URL
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: KIS_STOCK_PRICE_URL
        - name: KIS_STOCK_INDUSTRY_URL
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: KIS_STOCK_INDUSTRY_URL
        - name: APP_KEY1
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: APP_KEY1
        - name: APP_SECRET1
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: APP_SECRET1
        - name: APP_KEY2
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: APP_KEY2
        - name: APP_SECRET2
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: APP_SECRET2
        - name: APP_KEY3
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: APP_KEY3
        - name: APP_SECRET3
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: APP_SECRET3
        - name: KIS_STOCK_PRICE_TR_ID
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: KIS_STOCK_PRICE_TR_ID
        - name: KIS_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: secret-stock
              key: KIS_ENCRYPTION_KEY

      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: newstock-stock-auth-service
spec:
  selector:
    app: newstock-stock-auth
  ports:
    - protocol: TCP
      port: 8000           # 클러스터 내부에서 접근할 서비스 포트
      targetPort: 8000    # 컨테이너 내부 포트
  type: LoadBalancer      # 외부에서 접근할 수 있는 서비스 타입 (필요시 ClusterIP로 변경 가능)
