apiVersion: apps/v1
kind: Deployment
metadata:
  name: newstock-stock-news
  labels:
    app: newstock-stock-news
spec:
  replicas: 1 # 원하는 레플리카 수 설정
  selector:
    matchLabels:
      app: newstock-stock-news
  template:
    metadata:
      labels:
        app: newstock-stock-news
    spec:
      containers:
      - name: newstock-stock-news-container
        image: ocir.ap-singapore-2.oci.oraclecloud.com/axzbwuphhddr/newstocknews:TAG_PLACEHOLDER
        ports:
        - containerPort: 8002  # 스프링 부트 애플리케이션의 기본 포트
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m"  # 메모리 설정 등 스프링 부트 설정
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: newstock-stock-news-service
spec:
  selector:
    app: newstock-stock-news
  ports:
    - protocol: TCP
      port: 8002           # 클러스터 내부에서 접근할 서비스 포트
      targetPort: 8002    # 컨테이너 내부 포트
  type: ClusterIP      # 외부에서 접근할 수 있는 서비스 타입 (필요시 ClusterIP로 변경 가능)
