stages:
  - build
  - deploy

variables:
  OCI_REGION: "ap-singapore-2"
  OCI_KEY_FILE: "/home/ec2-user/.oci/oci_api_key.pem" # GitLab Runner에서 사용할 키 파일 경로
  OCI_REPO: "axzbwuphhddr/test"
  IMAGE_TAG: "latest"

# GitLab에서 저장한 OCI 인증 토큰을 사용
before_script:
  - echo "$OCI_AUTH_TOKEN" | docker login -u axzbwuphhddr/thswltjr12@gmail.com --password-stdin ocir.$OCI_REGION.oci.oraclecloud.com

build_service1:
  stage: build
  tags:
    - newstock-runner-arm # 사용할 Runner 태그
  script:
    - echo "Building service1..."
    - docker build -f test/Dockerfile -t ocir.$OCI_REGION.oci.oraclecloud.com/axzbwuphhddr/newstock-ocir:latest test/
    - docker push ocir.$OCI_REGION.oci.oraclecloud.com/axzbwuphhddr/newstock-ocir:latest
