stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the ServiceAccount project..."

deploy_job:
  stage: deploy
  script:
    - sudo -u ec2-user KUBECONFIG=/home/ec2-user/.kube/config kubectl apply -f deployment.yaml
  tags:
    - newstock-runner2
