stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying to OKE using Kubernetes ServiceAccount"
    - export KUBECONFIG=$HOME/.kube/config # 서비스 계정 토큰이 포함된 kubeconfig
    - kubectl get pods
    - kubectl run nginx --image=nginx
  tags:
    - shell-executor
