stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the ServiceAccount project..."

deploy_job:
  stage: deploy
  before_script:
    - echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config
  script:
    - echo "Deploying an nginx pod to the OKE cluster"
    - kubectl apply -f deployment.yaml
  tags:
    - newstock-runner
