stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the ServiceAccount project..."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying an nginx pod to the OKE cluster"
    - export KUBECONFIG=/home/ec2-user/.kube/config
    - kubectl run nginx --image=nginx
    - kubectl get pods # 클러스터 접근 확인

  tags:
    - shell-executor
