stages:
  - build
  - deploy

variables:
  OCI_REGION: "ap-singapore-2"
  OCI_KEY_FILE: "/home/ec2-user/.oci/oci_api_key.pem" # GitLab Runner에서 사용할 키 파일 경로
  OCI_REPO: "axzbwuphhddr/test"
  IMAGE_TAG: "latest"

# GitLab에서 저장한 OCI 인증 토큰을 사용
before_script:
  - echo "$OCI_AUTH_TOKEN" | docker login -u axzbwuphhddr/thswltjr12@gmail.com --password-stdin ocir.$OCI_REGION.oci.oraclecloud.com

build_service1:
  stage: build
  tags:
    - newstock-runner # 여기에 사용할 Runner 태그 추가
  script:
    - docker buildx create --use
    - echo "Building service1..."
    - docker buildx build --platform linux/arm64 -f test/Dockerfile -t ocir.$OCI_REGION.oci.oraclecloud.com/axzbwuphhddr/newstock-ocir:latest --push test/
# build_service2:
#   stage: build
#   script:
#     - echo "Building service2..."
#     - docker buildx build -f service2/Dockerfile -t ocir.$OCI_REGION.oci.oraclecloud.com/axzbwuphhddr/service2:latest --push .

# build_service3:
#   stage: build
#   script:
#     - echo "Building service3..."
#     - docker buildx build -f service3/Dockerfile -t ocir.$OCI_REGION.oci.oraclecloud.com/axzbwuphhddr/service3:latest --push .

