apiVersion: apps/v1
kind: Deployment
metadata:
  name: newstock-stock-frontend
  labels:
    app: newstock-stock-frontend
spec:
  replicas: 1  # 원하는 레플리카 수 설정
  selector:
    matchLabels:
      app: newstock-stock-frontend
  template:
    metadata:
      labels:
        app: newstock-stock-frontend
    spec:
      containers:
      - name: newstock-stock-frontend-container
        image: ocir.ap-singapore-2.oci.oraclecloud.com/axzbwuphhddr/newstockfrontend:TAG_PLACEHOLDER
        ports:
        - containerPort: 3000  # 스프링 부트 애플리케이션의 기본 포트
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: newstock-stock-frontend-service
spec:
  selector:
    app: newstock-stock-frontend
  ports:
    - protocol: TCP
      port: 3000           # 클러스터 내부에서 접근할 서비스 포트
      targetPort: 3000    # 컨테이너 내부 포트
  type: ClusterIP      # 외부에서 접근할 수 있는 서비스 타입 (필요시 ClusterIP로 변경 가능)
