apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Ingress Class 설정
  rules:
  - host: withhim-jenkins.site
    http:
      paths:
      - path: /member
        pathType: Prefix
        backend:
          service:
            name: newstock-stock-member-service
            port:
              number: 8001
      - path: /news
        pathType: Prefix
        backend:
          service:
            name: newstock-stock-news-service
            port:
              number: 8002
      - path: /stock
        pathType: Prefix
        backend:
          service:
            name: newstock-stock-stock-service
            port:
              number: 8003
