server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://lab.ssafy.com/thswltjr11/newstock-config.git
          # branch: main  # ?? ?? ???
          # username: your-github-username  # ??? ??
          # password: your-github-password  # ??? ??

#  profiles:
#    active: native

management:
  endpoints:
    web:
      exposure:
        include: health, info
