spring:
  profiles:
    include: feign
  application:
    name: news
  datasource:
  #    url: jdbc:mysql://3.38.182.23:3306/news
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: ssafy1234
  #    password: ssafy1234
    url: jdbc:mysql://svc.sel4.cloudtype.app:30947/news
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: kafka-service:9092
  data:
    redis:
      host: redis-service
      port: 6379

server:
  port: 8002
hbase:
  url: http://j11c207a.p.ssafy.io:9090


logging:
  level:
    com.ssafy.news.domain.service.client.StockClient: DEBUG
    org:
      hibernate:
        orm:
          jdbc:
            bind:
              trace
